version: "3"
services:
  rmd:
    build:
      context: .
      args:
        REQUIREMENTS: requirements-dev.txt
    depends_on:
      - "postgres"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command:
      [
        "/bin/sh",
        "-c",
        "wait-for-it.sh postgres:5432 -- app/manage.py migrate && app/manage.py runserver 0.0.0.0:8000",
      ]

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"