name: Check Black Formatting

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jpetrucciani/black-check@19.10b0
    - uses: cclauss/GitHub-Action-for-pytest@0.5.0
